// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home({articles}) {
//   console.log(articles)
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Hello next</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className='flex flex-col justify-center items-center'>
//         <h1 className="text-6xl font-bold text-center py-16">
//           Welcome to <a href="https://nextjs.org" className='text-[#0070f3]'>Next.js!</a>
//         </h1>

//         <p className="text-xl text-center py-4">
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className='flex flex-col sm:flex-row py-12 flex-wrap  justify-center items-center max-w-[800px]'>
//           {articles.map((article)=>(
//             <a href="https://nextjs.org/docs" className='m-[1rem] p-[1.5rem] text-left color-inherit border-2  rounded-lg border-solid-[#eaeaea] radius-[10px] max-w-[300px] max-h-[280px] ease duration-150 transition active:color-[#0070f3] active:border-[#0070f3]  hover:color-[#0070f3] hover:border-[#0070f3]  focus:color-[#0070f3] focus:border-[#0070f3] text-clip overflow-hidden'>
//             <h2 className='text-2xl font-bold '>{article.title} &rarr;</h2>
//             <p className=' my-2 leading-normal text-xl text-clip'>{article.body}</p>
//           </a>
//            ))}
//         </div>
//       </main>
//     </div>
//   )
// }

// export const getStaticProps = async () => {
//   const res = await fetch( `https://jsonplaceholder.typicode.com/posts?_limit=6`) 
//   const articles = await res.json()

//   return{
//     props: {
//       articles
//     }
//   }
// }
