import React from 'react'
import Head from 'next/head'

const news = () => {
  return (
    <div>
    <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    
        News</div>

  )
}

export default news